spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456


server:
  port: 8083

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9090/xxl-job-admin
