CREATE TABLE `timing_task3`  (
                                `id` int NOT NULL AUTO_INCREMENT,
                                `processid` int NOT NULL COMMENT '流程id',
                                `robotid` int NOT NULL,
                                `userid` int NOT NULL,
                                `tenant` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
                                `createtime` datetime NULL DEFAULT CURRENT_TIMESTAMP,
                                `lastupdatetime` datetime NULL DEFAULT CURRENT_TIMESTAMP,
                                `istiming` tinyint(1) NOT NULL COMMENT '是否定时',
                                `starttime` datetime NULL DEFAULT NULL,
                                `endtime` datetime NULL DEFAULT NULL,
                                `uninterrupted` tinyint(1) NOT NULL COMMENT '是否不间断运行',
                                `executecount` int NOT NULL DEFAULT 1 COMMENT '执行次数 1单次 2多次',
                                `crontab` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '间隔时间设置',
                                `robottype` int NOT NULL COMMENT '1 排队运⾏\n2 放弃运⾏',
                                `iscontinue` tinyint(1) NULL DEFAULT NULL COMMENT '子流程中断是否继续运行剩余流程',
                                `status` int NULL DEFAULT NULL COMMENT '状态 1 运行中 2待运行 3中断 4完成',
                                `sequence` int NOT NULL DEFAULT 0,
                                `progress` int NOT NULL DEFAULT 0,
                                `next_trigger_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `isrecordvideo` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否录屏',
                                `isdelete` tinyint(1) NOT NULL DEFAULT 0,
                                `isignoreerror` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否忽略异常 \n0 忽略\n1 不忽略',
                                `projectid` int NOT NULL DEFAULT 0 COMMENT '新版的工程id，processid弃用',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 171 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '定时任务' ROW_FORMAT = DYNAMIC;